name: ArmorStandStorage
version: 1.0
main: com.koopacraft.armorstandstorage.ArmorStandStorage
api-version: 1.13
description: Allows players to store items in armor stands
permissions:
  armorstandstorage.use:
    description: Allows players to use armor stand storage
    default: op 